services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        environment:
            - APP_ENV=local
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: my-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - app-network

    node:
        platform: linux/arm64/v8
        build:
            context: .
            dockerfile: Dockerfile.node
        image: my-laravel-node
        container_name: my-laravel-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - app-network

    db:
        image: postgres:alpine
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: weather
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - dbdata:/var/lib/postgres
        networks:
            - app-network
        ports:
            - "5433:5432"

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
